Flutter-Bounty-Hunters/static_shock

packages/static_shock_cli/README_PUBLISH.md, packages/static_shock_cli/bin/static_shock_cli.dart, packages/static_shock_cli/build.yaml, packages/static_shock_cli/lib/version.dart, packages/static_shock_cli/pubspec.lock, packages/static_shock_cli/pubspec.yaml
Add version checks and an upgrade command (Resolves #16)
The create and serve commands automatically check for newer versions on Pub:
```
Checking for newer versions of static_shock_cli...
New version of static_shock_cli is available: 0.1.0-dev.49 -> 0.0.1-dev.4
Creating a new Static Shock project...
Current directory: /Users/matt/Projects/static_shock/packages/static_shock_cli
```
A standalone `version` command is also available:
```
% shock version
Your current version of static_shock_cli is: 0.1.0-dev.49
Checking for newer versions of static_shock_cli on Pub...
A new version is available: 0.1.0-dev.49 -> 0.0.1-dev.4
```
And an `upgrade` command is available, which checks for a new version, and then upgrades the local version if a new one is available.
=> Add version checks and an upgrade command (Resolves #16)

packages/static_shock/lib/src/data.dart, packages/static_shock/lib/src/files.dart, packages/static_shock/lib/src/source_files.dart, packages/static_shock/lib/src/static_shock.dart, packages/static_shock/pubspec.yaml, packages/static_shock_docs/source/guides/_data.yaml, packages/static_shock_docs/source/guides/add-a-page.md, packages/static_shock_docs/source/guides/compile-sass.md, packages/static_shock_docs/source/guides/copy-assets.md, packages/static_shock_docs/source/guides/create-rss-feed.md, packages/static_shock_docs/source/guides/display-a-menu-in-a-page.md, packages/static_shock_docs/source/guides/use-remote-css-and-js.md, packages/static_shock_docs/source/index.jinja
Page data is inherited from _data.yaml files in the source set (Resolves #43)
Replaced the repeated menu definition for the "Guides" pages with a single `_data.yaml` in the `/guides` directory.
=> Page data is inherited from _data.yaml files in the source set (Resolves #43)

packages/static_shock_cli/bin/static_shock_cli.dart, packages/static_shock_cli/pubspec.lock, packages/static_shock_cli/pubspec.yaml
Add 'shock build' command (Resolves #39)
The command attempts to match an executable file with the same name as the package. If it can't find that, it looks for `bin/main.dart`.
=> Add 'shock build' command (Resolves #39)

packages/static_shock_cli/bin/static_shock_cli.dart, packages/static_shock_cli/lib/src/dev_server.dart, packages/static_shock_cli/lib/src/website_builder.dart, packages/static_shock_cli/lib/static_shock_cli.dart, packages/static_shock_cli/pubspec.lock, packages/static_shock_cli/pubspec.yaml
shock serve now auto-refreshes HTML pages when any source file changes, also port is now configurable (Resolves #41)
During `shock serve`, the `/source` directory is watched. Any reported file system change triggers a full website rebuild.
The `shock serve` dev server now intercepts all HTML files that it serves and injects some JavaScript that connects a websocket with the dev server. Every time `shock serve` rebuilds the website, it notifies all registered websockets that a change has occurred, and the injected JavaScript refreshes the whole page.
Users can now specify the server port with the `--port` flag. Additionally, if the desired port is in use, the server will try to find a nearby open port. Port searching can be disabled with the `--no-find-open-port` flag.
In the future, it …
=> shock serve now auto-refreshes HTML pages when any source file changes, also port is now configurable (Resolves #41)

packages/static_shock/lib/src/pipeline.dart, packages/static_shock/lib/src/plugins/jinja.dart, packages/static_shock/lib/src/plugins/markdown.dart, packages/static_shock/lib/src/static_shock.dart
Allow arbitrary template functions, which makes it possible to convert markdown front matter properties to HTML within a template (Resolves #64)
Front Matter properties can be encoded as Markdown and used as HTML by translating those properties within a page template:
```jinja
<html>
<body>
<p>{{ md(my_property) }}</p>
</body>
</html>
```
=> Allow arbitrary template functions, which makes it possible to convert markdown front matter properties to HTML within a template (Resolves #64)

packages/static_shock/lib/src/pages.dart, packages/static_shock/lib/src/plugins/jinja.dart, packages/static_shock_cli/lib/src/dev_server.dart, packages/static_shock_docs/source/_includes/components/navbar.jinja, packages/static_shock_docs/source/directory.jinja, packages/static_shock_docs/source/guides/_data.yaml, packages/static_shock_docs/source/guides/add-a-page.md, packages/static_shock_docs/source/guides/compile-sass.md, packages/static_shock_docs/source/guides/copy-assets.md, packages/static_shock_docs/source/guides/create-a-plugin.md, packages/static_shock_docs/source/guides/create-rss-feed.md, packages/static_shock_docs/source/guides/deploy-to-github-pages.md, packages/static_shock_docs/source/guides/directory-of-pages.md, packages/static_shock_docs/source/guides/display-a-menu-in-a-page.md
Jinja templates can query all pages, as well as all pages with a given tag. This PR adds the ability to sort all returned pages by a given page property, as well as ascending or descending result order.
Before this PR we seemed to be missing a way to query all pages. This PR adds all page access to Jinja templates.
This PR adds a top-level page to the Docs website called "Directory" which uses the tag queries with ascending and descending order.
This PR adds a Docs guide showing how to display a directory of pages based on a page query.
=> Make pages sortable (Resolves #66)

packages/static_shock/lib/src/pages.dart, packages/static_shock/lib/src/pipeline.dart, packages/static_shock/lib/src/plugins/drafting.dart, packages/static_shock/lib/src/plugins/jinja.dart, packages/static_shock/lib/src/plugins/menus.dart, packages/static_shock/lib/src/static_shock.dart, packages/static_shock/lib/static_shock.dart, packages/static_shock/pubspec.yaml, packages/static_shock_cli/bin/static_shock_cli.dart, packages/static_shock_cli/lib/src/website_builder.dart, packages/static_shock_cli/pubspec.lock, packages/static_shock_docs/bin/static_shock_docs.dart, packages/static_shock_docs/pubspec.lock, packages/static_shock_docs/source/_includes/layouts/guides.jinja, packages/static_shock_docs/source/guides/_data.yaml, packages/static_shock_docs/source/guides/draft-articles.md
Added draft-mode plugin to remove page drafts, also added filters and tests to assemble menus based on page existence (Resolves #71)
This PR includes:
* A new guide about draft mode
* Exclusion of pages during build when a property called `draft` is `true` (can be turned off with the plugin config)
* Jinja filters and tests that help construct menus in Jinja templates given that some pages might not exist
* `shock build` and `shock serve` now pass on any extra arguments so that an app might implement the concept of a "preview" mode when building or serving
=> Added draft-mode plugin to remove page drafts, also added filters and tests to assemble menus based on page existence (Resolves #71)

packages/static_shock/lib/src/plugins/markdown.dart, packages/static_shock_docs/source/_includes/layouts/guides.jinja, packages/static_shock_docs/source/guides/add-a-page.md, packages/static_shock_docs/source/guides/compile-sass.md, packages/static_shock_docs/source/guides/copy-assets.md, packages/static_shock_docs/source/guides/create-a-plugin.md, packages/static_shock_docs/source/guides/create-rss-feed.md, packages/static_shock_docs/source/guides/deploy-to-github-pages.md, packages/static_shock_docs/source/guides/directory-of-pages.md, packages/static_shock_docs/source/guides/display-a-menu-in-a-page.md, packages/static_shock_docs/source/guides/draft-articles.md, packages/static_shock_docs/source/guides/use-remote-css-and-js.md, packages/static_shock_docs/source/styles/guides.scss, packages/static_shock_docs/source/styles/theme.scss
Publish table-of-contents data with every Markdown page.
The Markdown plugin adds root level data to the `Page` data structure with the key "tableOfContents".
Example of "tableOfContents" data, accessible from templates:
```
"tableOfContents": {
"items": [{
"title": "...",
"sectionId": "...",
"level": 0,
}],
"isEmpty": false,
"isEmptyBeyondLevel": (level) => {},
"hasMultipleBeyondLevel": (level) => {},
"linkCountBeyondLevel": (level) => {},
"renderHtmlList": ({startingLevel}) => {},
}
```
=> Publish table-of-contents data with every Markdown page.

packages/static_shock_cli/lib/src/dev_server.dart, packages/static_shock_cli/pubspec.lock, packages/static_shock_cli/pubspec.yaml
Move Mason Logger call during rebuild to avoid apparent logger race condition exception (Resolves #76)
The original issue #76 looks like it was probably already fixed but I was running an older version of the static_shock_cli. I wasn't able to recreate the crash when running the latest version of the CLI from local sources.
I did, however, move the mason_logger log statement such that it never attempts to log anything until after we've verified that we're not already building the website. There seems to be some kind of race condition with the logger that's causing an exception. Rather than repeatedly catch that exception and warn the user, I moved the log statement to a safe location.
I filed https://github.com/felangel/mason/issues/1280 with mason_logger.
This PR also upgrades …
=> Move Mason Logger call during rebuild to avoid apparent logger race condition exception (Resolves #76)

packages/static_shock_docs/source/_includes/components/githubCornerLink.jinja, packages/static_shock_docs/source/_includes/layouts/guides.jinja, packages/static_shock_docs/source/_includes/layouts/top-level-page.jinja, packages/static_shock_docs/source/index.jinja, packages/static_shock_docs/source/styles/homepage.scss
Added persistent GitHub icon in top-right corner, also added GitHub button on homepage (Resolves #60)
=> Added persistent GitHub icon in top-right corner, also added GitHub button on homepage (Resolves #60)

packages/static_shock/lib/src/plugins/jinja.dart, packages/static_shock/pubspec.yaml
Added a 'formatDateTime' Jinja filter to format incoming date times (Resolves #90)
Example: `{{ date | formatDateTime(to = "MMMM dd, yyyy") }}`
=> Added a 'formatDateTime' Jinja filter to format incoming date times (Resolves #90)

packages/static_shock_cli/bin/static_shock_cli.dart
[CLI] - Improved graceful failure when passing bad arguments to CLI commands (Resolves #84)
When a `UsageException` is thrown for bad argument usage, that exception is now caught, and only the `message` and `usage` is printed to the terminal. The stacktrace isn't printed because the user shouldn't see that.
=> [CLI] - Improved graceful failure when passing bad arguments to CLI commands (Resolves #84)

packages/static_shock_cli/lib/src/dev_server.dart, packages/static_shock_cli/pubspec.yaml
Fix recurring dev server crashes (Resolves #76)
My hypothesis is that we were running into race conditions when accessing the file system between the website build behavior and the websites refreshing their files. This PR waits until all queued builds are complete before telling connected websites to refresh.
=> Fix recurring dev server crashes (Resolves #76)

packages/static_shock/lib/src/plugins/markdown.dart, packages/static_shock/lib/src/static_shock.dart
[Shock] - Expose all Markdown-to-HTML render options at plugin level. Also notify user if a page has unknown renderer.
The impetus for the Markdown rendering options is that I was trying to get a page to render a combination of Markdown and Jinja, but the Markdown renderer kept escaping characters in the Jinja syntax. The setting for escaping characters is available at the point of requesting a Markdown-to-HTML conversion. All of those options are now elevated to the plugin level.
I also accidentally used the wrong syntax for specifying multiple renderers. I couldn't figure out why the page wasn't rendering. To help with that in the future, I added a warning when a page is loaded but fails to find at least one page renderer.
=> [Shock] - Expose all Markdown-to-HTML render options at plugin level. Also notify user if a page has unknown renderer.

packages/static_shock/lib/src/plugins/tailwind_css.dart, packages/static_shock/lib/src/static_shock.dart, packages/static_shock/lib/static_shock.dart, packages/static_shock_docs/source/guides/_data.yaml, packages/static_shock_docs/source/guides/compile-tailwind.md
Added plugin for Tailwind CSS (Resolves #145)
This plugin simply creates a place in the generation process to call out to the Tailwind CSS binary tool: https://tailwindcss.com/blog/standalone-cli
It's up to the user to include an appropriate Tailwind binary in their project.
=> Added plugin for Tailwind CSS (Resolves #145)

packages/static_shock/lib/src/files.dart, packages/static_shock/lib/src/plugins/pretty_urls.dart, packages/static_shock/test/plugins/pretty_urls_test.dart
Fix: Prettify URLs for pages with explicit index files (Resolves #152)
Consider a file like `source/posts/news/some-event/index.md`. It should map to URL `/posts/news/some-event/` but instead was mapping to `/posts/news/some-event/index.html`.
=> Fix: Prettify URLs for pages with explicit index files (Resolves #152)

packages/static_shock/lib/src/plugins/menus.dart
[Docs] - Fix: Guide menu not showing.
A recent change to the `url` property of `Page`s requires a leading `/`, which was missing from the Jinja template function that filters out non-existent pages. I.e., the filter thought none of the pages existed, when they do.
=> [Docs] - Fix: Guide menu not showing.

packages/static_shock/lib/src/plugins/jinja.dart
[Shock] - Added Jinja filter called 'pathRelativeToPage' to build URLs on top of page URL (Relates to #164)
This PR doesn't actually resolve #164. When I worked on the problem, I found that the `Page` `url` property was giving us just the path, e.g., `/posts/my-post/`. We don't have any official access to the root domain, so there's no way to solve #164 without first deciding where the domain name should officially live. I didn't want to tackle that right at this moment.
With this approach, assuming a website defines it's own data property called `homepage_url`, a URL can be built as follows:
```jinja
{{ homepage_url }}{{ "images/photo.png" | pathRelativeToPage }}
```
We should still make this much easier in the future, but this is enough to unblock some other work.
=> [Shock] - Added Jinja filter called 'pathRelativeToPage' to build URLs on top of page URL (Relates to #164)

melos_static_shock.iml, packages/static_shock/lib/src/assets.dart, packages/static_shock/lib/src/cache.dart, packages/static_shock/lib/src/pipeline.dart, packages/static_shock/lib/src/plugins/drafting.dart, packages/static_shock/lib/src/plugins/github.dart, packages/static_shock/lib/src/plugins/jinja.dart, packages/static_shock/lib/src/plugins/markdown.dart, packages/static_shock/lib/src/plugins/pretty_urls.dart, packages/static_shock/lib/src/plugins/pub_package.dart, packages/static_shock/lib/src/plugins/redirects.dart, packages/static_shock/lib/src/plugins/rss.dart, packages/static_shock/lib/src/plugins/sass.dart, packages/static_shock/lib/src/plugins/tailwind_css.dart, packages/static_shock/lib/src/plugins/website_screenshots.dart, packages/static_shock/lib/src/static_shock.dart, packages/static_shock/lib/static_shock.dart, packages/static_shock/pubspec.yaml, packages/static_shock_cli/lib/src/dev_server.dart, packages/static_shock_docs/.gitignore, packages/static_shock_docs/bin/static_shock_docs.dart, packages/static_shock_docs/source/_data.yaml, packages/static_shock_docs/source/guides/_data.yaml, packages/static_shock_docs/source/guides/website-screenshots.md, packages/static_shock_docs/source/index.jinja, template_sources/template_blog/.gitignore, template_sources/template_docs_multi_page/.gitignore, template_sources/template_empty/.gitignore
Add staticshock.io showcase, WebsiteScreenshotsPlugin, and a Static Shock build cache (Resolves #161)(Resolves #117)
The `WebsiteScreenshotsPlugin` takes screenshots for any number of websites that are requested.
Each plugin is given a `StaticShockCache` for caching files between builds, which was important to avoid very long build times when taking screenshots.
=> Add staticshock.io showcase, WebsiteScreenshotsPlugin, and a Static Shock build cache (Resolves #161)(Resolves #117)

packages/static_shock_docs/bin/static_shock_docs.dart
[Docs] - Turn on screenshots plugin for CI again, use committed screenshot images instead of generating them.
=> [Docs] - Turn on screenshots plugin for CI again, use committed screenshot images instead of generating them.

packages/static_shock_docs/source/concepts/_data.yaml, packages/static_shock_docs/source/concepts/how-it-works/plugins.md, packages/static_shock_docs/source/concepts/how-it-works/the-pipeline.md, packages/static_shock_docs/source/concepts/jinja-templates/basic-syntax.md, packages/static_shock_docs/source/concepts/jinja-templates/filters.md, packages/static_shock_docs/source/concepts/jinja-templates/functions.md, packages/static_shock_docs/source/concepts/jinja-templates/jinja-plugin.md, packages/static_shock_docs/source/concepts/jinja-templates/tests.md, packages/static_shock_docs/source/concepts/jinja-templates/what-is-jinja.md, packages/static_shock_docs/source/concepts/markdown/overview.md
[Docs] - Added references for Jinja and Markdown (Resolves #194)
Docs are added to `/concepts/jinja-templates/` and `/concepts/markdown/`.
=> [Docs] - Added references for Jinja and Markdown (Resolves #194)

packages/static_shock/lib/src/data.dart, packages/static_shock/lib/src/pipeline.dart, packages/static_shock/lib/src/plugins/drafting.dart, packages/static_shock/lib/src/plugins/jinja.dart, packages/static_shock/lib/src/plugins/links.dart, packages/static_shock/lib/src/plugins/menus.dart, packages/static_shock/lib/src/static_shock.dart, packages/static_shock/lib/static_shock.dart, packages/static_shock/test/plugins/links_test.dart, packages/static_shock/test/plugins/pretty_urls_test.dart, packages/static_shock/test/plugins/redirects_test.dart, packages/static_shock_cli/lib/src/commands/serve_command.dart, packages/static_shock_cli/lib/src/dev_server.dart, packages/static_shock_docs/bin/static_shock_docs.dart, packages/static_shock_docs/source/concepts/_data.yaml, packages/static_shock_docs/source/concepts/directory.jinja, packages/static_shock_docs/source/concepts/how-it-works/assets.md, packages/static_shock_docs/source/concepts/how-it-works/plugins.md, packages/static_shock_docs/source/contributing/_data.yaml, packages/static_shock_docs/source/contributing/directory.jinja, packages/static_shock_docs/source/contributing/getting-started/work-on-an-issue.md, packages/static_shock_docs/source/guides/_data.yaml, packages/static_shock_docs/source/guides/validate-links.md, packages/static_shock_docs/source/index.jinja
Add `LinksPlugin` to validate all anchor tag links in website (Resolves #183)
Added `basePath` property to the `StaticShockPipelineContext`.
Added `buildMode` to `StaticShock` and to `StaticShockPipelineContext` so that Static Shock and plugins can make decisions based on building for production vs development.
Added a `cliArguments` property to the `StaticShock` object, which is used to parse standard Static Shock arguments. The CLI arguments are also forwarded to the `StaticShockPipelineContext` so that they're available to plugins, allowing plugins to also utilize CLI arguments for configuration. `StaticShock` parses the build mode from the CLI args, defaulting to `production`.
Added an `ErrorLog` to `StaticShockPipelineContext` so that plugins can report warnings, which are reported …
=> Add LinksPlugin to validate all anchor tag links in website (Resolves #183)

packages/static_shock/lib/src/plugins/links.dart, packages/static_shock/lib/src/static_shock.dart, packages/static_shock/test/plugins/links_test.dart, packages/static_shock_cli/lib/src/commands/build_command.dart, packages/static_shock_docs/source/guides/_data.yaml, packages/static_shock_docs/source/guides/find-missing-pages.md
Expand LinksPlugin to find missing pages since last build (Resolves #184)
CLI: Adds parsing of "--dev" and "--production" to set build mode, which is easier to type than "--build-mode production".
=> Expand LinksPlugin to find missing pages since last build (Resolves #184)
